name: prettier bot

on:
  push:
  pull_request:
    branches: 
      - stale

jobs:
  holderBot:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      workflows: write
      actions: write
      security-events: write
    steps: 
      - uses: actionsx/prettier@v2
        with:
          args: --write . --list-different
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prettier Bot
          commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: antojago5@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Hardianto <hardianto-cpu@github.com> # defaults to author of the commit that triggered the run
